# Generated by Django 5.1.1 on 2024-09-24 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='user_nickname',
            new_name='user_id',
        ),
    ]
